---
- name: "Determine if /etc/resolv.conf is a Symlink."
  stat:
    path: /etc/resolv.conf
  register: common_resolv_symlink_status

- name: "Remove Symlink on /etc/resolv.conf for Ubuntu."
  file:
    path: /etc/resolv.conf
    state: absent
  when: common_resolv_symlink_status.stat.islnk is defined and common_resolv_symlink_status.stat.islnk

- name: "Make sure /etc/resolv.conf is modifiable for this play."
  command: chattr -i /etc/resolv.conf
  when: common_resolv_symlink_status.stat.islnk is defined and not common_resolv_symlink_status.stat.islnk

- name: "Configure DNS Servers for Host."
  template:
    src: resolv.conf.j2
    dest: /etc/resolv.conf
    backup: 'true'
    mode: 0644
    owner: root
    group: root
    setype: net_conf_t

- name: "Make sure /etc/resolv.conf is not modifiable by anyone."
  command: chattr +i /etc/resolv.conf
