---
- name: "Configure shopt Preferences."
  ansible.builtin.lineinfile:
    dest: /etc/bashrc
    line: "{{ item }}"
    create: 'true'
  with_items: "{{ shopt_options }}"

- name: "Configure Bash Completion."
  ansible.builtin.blockinfile:
    dest: /etc/bashrc
    create: 'true'
    marker: "# {mark} ANSIBLE MANAGED BLOCK"
    content: |
     if ! shopt -oq posix; then
        if [ -f /usr/share/bash-completion/bash_completion ]; then
           . /usr/share/bash-completion/bash_completion
        elif [ -f /etc/bash_completion ]; then
           . /etc/bash_completion
        fi
     fi

- name: "Enable EPEL Repositories."
  ansible.builtin.package:
    name: epel-release
    state: present
  when: common_epel_enabled and ansible_distribution == "CentOS"
