---
- name: "Make sure timezone package is installed."
  ansible.builtin.package:
    name: "{{ common_timezone_package }}"
    state: present

- name: "Check for a zoneinfo file."
  ansible.builtin.stat:
    path: /usr/share/zoneinfo/{{ common_timezone }}
  register: common_zoneinfo

- name: "Alert if zoneinfo is not there."
  ansible.builtin.fail: msg="{{ common_timezone }} is not valid (/usr/share/zoneinfo/{{ common_timezone }} does not exist)"
  when: not (common_zoneinfo.stat.exists is defined and common_zoneinfo.stat.exists)

- name: "Symlink the correct localtime (/etc/localtime)."
  ansible.builtin.file:
    src: /usr/share/zoneinfo/{{ common_timezone }}
    dest: /etc/localtime
    force: 'true'
    state: link
    owner: root
    group: root
    mode: 0644
  when: common_zoneinfo.stat.exists is defined and common_zoneinfo.stat.exists
