---
- name: "Configure VIM."
  ansible.builtin.lineinfile:
    dest: "{{ common_vimrc_path }}"
    line: "let g:skip_defaults_vim = 1"
    regexp: "(# |^)let g:skip_defaults_vim.*"
    state: present
    backup: 'true'
    create: 'true'
